### ISSUE TITLE
Basic directory structure

### ISSUE THREAD

**Issue by awlostowski-noaa** [Lynker-Tech/NIDIS_drought#4]
(@SnowHydrology and @rachel-lynker) Opening this issue to converse on basic directory structure. I will start by proposing the following: 

- `/NIDIS_drought`
   - `/tidy_data` - only store tidy RData files, derived from workflows in [`drought_data_processing`](https://github.com/Lynker-Tech/drought_data_processing. The initial Git allocation is 1 GB. If we restrict the contents of this directory to only tidy data, we might not bump up against this. If we do, we can pay for additional storage. Also, Git LFS will allow us to track versions of these data sets. 
       - `/impacts`
           - sector specific subdirectories
       - `/indicators`
           - `/met` (processed met/hydro observations, e.g. snow, temp, precip, etc)
           - `/derived_indices` (e.g. PDSI, SPI, etc.)
   - `/models` - subdirectories will contain R code for constructing, evaluating, and visualizing impact specific models. Suggest organizing by sector and impact. 
       - `/forest_resources`
       - `/recreation`
       - `/water_supply` (sector level)0
           - `/annual_reservoir_inflow` (impact level)
               - `/<model_type>` (e.g. Random Forest)
               - `/output` - store tidy model output as RData files
               - `/viz` - scripts for visualizing critical model results. I'd like to see if we can contain `ggplot()` calls in their own scripts so we don't need to weed through modeling scripts to find where to edit/create figs. 
       - `/etc`
   - `/reviews` - contain literature review draft with figures, transposed in to markdown. Transcribed stakeholder interviews. Memos synthesizing stakeholder interviews.

**Comment by SnowHydrology** [comment]
@awlostowski-noaa This looks great. I have a few small suggestions:

- `/tidy_data` becomes `/data` to avoid confusion on what "tidy" means
- We add `/hydro` as a separate sub-directory
- Suggest we port over the current [lit review directory](https://github.com/rachel-lynker/CPO_coping_with_drought) as a subdirectory in `/reviews`

**Comment by SnowHydrology** [comment]
@awlostowski-noaa Working on directory structure now. Will associate this issue with a pull request when done.
